version: '3.7'

services:
  be:
    container_name: koa-lit_be
    build:
      context: ./koa-lit-docker-demo-be
    volumes:
      - ./koa-lit-docker-demo-be:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev # for development mode
    env_file:
      - .env
    networks:
      - koa-lit_webnet
    depends_on:
      - postgres
  # client:
  #   container_name: client
  #   build:
  #     context: ./party-haan-react
  #   #   target: development
  #   volumes:
  #     - ./party-haan-react:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${CLIENT_PORT}:${CLIENT_PORT}
  #   command: npm start
  #   env_file:
  #     - .env
  #   networks:
  #     - webnet
  postgres:
    container_name: koa_postgres
    image: postgres:12
    networks:
      - koa-lit_webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  koa-lit_webnet:
volumes:
  pgdata:
